### ISSUE TITLE
Problems with the 1.9.0 xpert version

### ISSUE THREAD

**Issue by S6NXGOD** [xpert-framework/xpert-framework#17]

**Comment by S6NXGOD** [comment]
Is it possible to make an archetype available?

**Comment by S6NXGOD** [comment]
When I create the project with the "war" available, i make the necessary changes for the operation of the primefaces and modify the dependencies of "pom.xml". However, i can't enjoy the components of the 7.0.0 primefaces, apparently they are still out of date.

**Comment by ayslanms** [comment]
Migration Guide for primefaces 7.0.0:

https://github.com/xpert-framework/xpert-framework/wiki/Guia-de-Migra%C3%A7%C3%A3o
