### ISSUE TITLE
Como faço para mudar os ícones dos menus?

### ISSUE THREAD

**Issue by S6NXGOD** [xpert-framework/xpert-framework#18]
Eu sei que para mudar nomes e criar sub-menus é em "Geração Permissão", porém, como eu faço para pôr ícones no menu.

Por exemplo:
No menu "Inicial", tem o ícone da casinha. Se eu criar um menu "cadastro" por exemplo, como posso pôr um ícone?

P.S:
Comecei a usar o framework a pouquíssimo tempo, ainda estou um pouco leigo. Desde já, agradeço a compreensão.

**Comment by ayslanms** [comment]
Você pode criar na classe `Permissao.java`um campo para o Icone, exemplo:

```java
private String icone;
```

Na classe `UsuarioMenuBO.java` definir o icone na parte que o menu/submenu é criado:

```java
 DefaultMenuItem item = new DefaultMenuItem();
 item.setIcon(permissao.getIcone());
...

submenu = new DefaultSubMenu();
submenu.setIcon((permissao.getIcone());

```

Depois disso é só criar o Icone na tela de cadastro de permissão e informar os valores conforme o primefaces espera.

**Comment by S6NXGOD** [comment]
Deu certo! Obrigado pelo feedback.
